### ISSUE TITLE
Repo still shows 5.6.3 requirement

### ISSUE THREAD

**Issue by yosun** [googlevr/poly-toolkit-unity#17]
Repo still shows 5.6.3 is required - seems to work fine with 2017+
Are there any specific features that aren't supported with the later versions of Unity? 

https://gyazo.com/25bd9e83a53e5da19c3c762025d40964

**Comment by anokta** [comment]
Hi yosun,

Unity 5.6.3 is only a **minimum** requirement, i.e., Poly Toolkit should work as expected - *if not better* - with the later versions of Unity including the latest version 2018.1.6.

I do, however, agree that warning may sound misleading. Thanks for letting us know.

Closing the bug, but please feel free to comment, re-open or create another issue, in case you have any other concerns.

Cheers
