### ISSUE TITLE
[2018.3.0b1] Multiple Brush shader errors

### ISSUE THREAD

**Issue by iBicha** [googlevr/poly-toolkit-unity#19]
Won't compile on the new Unity beta 2018.3.0b1

Affected shaders:

'Brush/Particle/Snow'
'Brush/Visualizer/Dots'
'Brush/Particle/Smoke'
'Brush/Particle/Stars'
'Brush/Particle/Bubbles'
'Brush/Particle/Embers'

**Comment by dubois** [comment]
I tried just now with 2018.3.0b12 and didn't see any errors. Can you paste some of them?

**Comment by dill0wn** [comment]
I'm seeing the same thing in 2018.3.3f1
Error occurs when building an .apk, with graphics api set to auto in the player settings.

Here is a sample of one of the errors:
```
Shader error in 'Brush/Particle/Bubbles': Input signature parameter SV_VertexID (1-based Entry 0) type must be a scalar uint. at line 80 (on gles)

Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING
```

It seems to be caused by any of the shaders using the `ParticleVertexWithSpread_t` struct from Particles.cginc.

```
#define ParticleVertexWithSpread_t ParticleVertex_t

struct ParticleVertex_t {
  uint vid : SV_VertexID;
  float4 corner : POSITION;     // pos: corner of randomly-oriented quad
  float3 center : TEXCOORD1;
  fixed4 color : COLOR;
  float4 texcoord : TEXCOORD0;  // xy: texcoord   z: rotation   w: birth time
};
```

**Comment by yosun** [comment]
Note: works in editor. Error seems to occur only when building.

**Comment by dubois** [comment]
Please see https://github.com/googlevr/poly-toolkit-unity/issues/28
