### ISSUE TITLE
Poly Toolkit tab\menu doesn't appear after installing from AssetStore

### ISSUE THREAD

**Issue by ivanmkc** [googlevr/poly-toolkit-unity#2]
I installed this through the asset store and my Unity IDE hasn't changed.

**Comment by btco** [comment]
Weird. There should be a "Poly" menu after importing the toolkit.
Did you notice any compile errors in the console?
Also, which version of Unity are you using?

**Comment by btco** [comment]
Note: if you are using Unity 2018, this is because Unity 2018 requires you to first enable the "unsafe code" option, because Poly Toolkit uses unsafe{} blocks for performance.

To do this go to Player Settings and enable the "Unsafe code" checkbox under "Other settings".
