### ISSUE TITLE
Errors if PolyToolkit moved into a subdirectory of assets

### ISSUE THREAD

**Issue by andybak** [googlevr/poly-toolkit-unity#21]
I usually have a "3rd Party" directory in assets so I can easily .gitignore large assets such as Poly Toolkit.

However this breaks Poly Toolkit.. Multiple errors in the console and the browse window is blank.

 (tested on Unity 2018.2.12f1)

**Comment by bhylak** [comment]
haven't experienced this on 2018.1.9

**Comment by anokta** [comment]
This issue should have been resolved via 447ca02d07029f9d46e0755a7e9a5abbf1669f75 already. Could you verify if you could reproduce this with the latest release version? Otherwise, closing the bug.
