### ISSUE TITLE
Shader urls are not valid

### ISSUE THREAD

**Issue by iBicha** [googlevr/poly-toolkit-unity#5]
Selecting `Assets/PolyToolkit/Resources/PtSettings` => `Surface Shader Materials`

we can see 3 with urls:
https://vr.google.com/shaders/w/gvrss/paper.json
https://vr.google.com/shaders/w/gvrss/gem.json
https://vr.google.com/shaders/w/gvrss/glass.json

None of em work.

**Comment by mitchellcairns** [comment]
Noticed this as well. Also when importing assets, everything is just red... could have to do with this?

**Comment by btco** [comment]
Those URLs are never actually fetched. They are used just for string comparisons in Poly Toolkit (so they just look like URLs, but in reality are just fancy-looking shader IDs). So the fact that they 404 isn't a sign of a problem.

@mitchellcairns Does that happen with all assets? Can you share the link to the asset that exhibits this problem?

**Comment by iBicha** [comment]
Alright, even though they are slightly misleading, I'll close this issue since there isnt any.
Thanks for the clarification!
